### PR TITLE
Fix authentication issue

### PR DESCRIPTION
**Pull request by Vincent--**
Ensure we are authenticated before trying to use the REST API
The first call return http 200 with no response but set the cookie, session, etc. 
The second call is the "real" call

### CODE REVIEW

**Comment by Vincent--** [comment]
Fix https://github.com/mlf4aiur/SublimeConfluence/issues/3

**Comment by mlf4aiur** [comment]
Thanks!

**Comment by Vincent--** [comment]
Thank you for this nice plugin 👍 
Could we have a release for packages control too?

**Comment by mlf4aiur** [comment]
Sure, just did that.

**Comment by Vincent--** [comment]
👍

**Pull request merged**
